### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by gedw99** [ilidemi/giorefreshrate#1]
good stuff @ilidemi 

i tried it on a newer android and a massive difference. Scrolling is so much faster now in gio. !!

**Comment by ilidemi** [comment]
Glad you found it helpful! Smooth scrolling is a treat

**Comment by gedw99** [comment]
We could push it upstream . If you don’t have time I can ..

**Comment by ilidemi** [comment]
That may happen, here's a thread on the mailing list: https://lists.sr.ht/~eliasnaur/gio/%3CCAPBnN5ZpZ_a5FmA3FdeXu+_pY63ruuCP6_MLC55ALaZ7nZJhvQ%40mail.gmail.com%3E

**Comment by gedw99** [comment]
Great !! Thanks for letting me know .
